pub mod trading_hours {

    use rocket::serde::{json::Value, Deserialize, Serialize};

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ExchangeTradingHours {
        pub name: Name,
        #[serde(rename = "short_name")]
        pub short_name: ShortName,
        pub website: Website,
        #[serde(rename = "market_open")]
        pub market_open: MarketOpen,
        #[serde(rename = "market_close")]
        pub market_close: MarketClose,
        #[serde(rename = "lunchbreak_start")]
        pub lunchbreak_start: LunchbreakStart,
        #[serde(rename = "lunchbreak_end")]
        pub lunchbreak_end: LunchbreakEnd,
        #[serde(rename = "opening_auction_start")]
        pub opening_auction_start: OpeningAuctionStart,
        #[serde(rename = "opening_auction_end")]
        pub opening_auction_end: OpeningAuctionEnd,
        #[serde(rename = "closing_auction_start")]
        pub closing_auction_start: ClosingAuctionStart,
        #[serde(rename = "closing_auction_end")]
        pub closing_auction_end: ClosingAuctionEnd,
        pub timezone: Timezone,
        pub flag: Flag,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Name {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: String,
        #[serde(rename = "STU")]
        pub stu: String,
        #[serde(rename = "ENX")]
        pub enx: String,
        #[serde(rename = "TWO")]
        pub two: String,
        #[serde(rename = "HAM")]
        pub ham: String,
        #[serde(rename = "MUN")]
        pub mun: String,
        #[serde(rename = "DUS")]
        pub dus: String,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: String,
        #[serde(rename = "GER")]
        pub ger: String,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: String,
        #[serde(rename = "HAN")]
        pub han: String,
        #[serde(rename = "SAU")]
        pub sau: String,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: String,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: String,
        #[serde(rename = "OSL")]
        pub osl: String,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: String,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: String,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: String,
        #[serde(rename = "AMS")]
        pub ams: String,
        #[serde(rename = "ATH")]
        pub ath: String,
        #[serde(rename = "PNK")]
        pub pnk: String,
        #[serde(rename = "AQS")]
        pub aqs: String,
        #[serde(rename = "CPH")]
        pub cph: String,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: String,
        #[serde(rename = "NCM")]
        pub ncm: String,
        #[serde(rename = "NMS")]
        pub nms: String,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: String,
        #[serde(rename = "EBS")]
        pub ebs: String,
        #[serde(rename = "ASE")]
        pub ase: String,
        #[serde(rename = "BUE")]
        pub bue: String,
        #[serde(rename = "SGO")]
        pub sgo: String,
        #[serde(rename = "CNQ")]
        pub cnq: String,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: String,
        #[serde(rename = "TLV")]
        pub tlv: String,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: String,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: String,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: String,
        #[serde(rename = "LIS")]
        pub lis: String,
        #[serde(rename = "LIT")]
        pub lit: String,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: String,
        #[serde(rename = "ICE")]
        pub ice: String,
        #[serde(rename = "RIS")]
        pub ris: String,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: String,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ShortName {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: String,
        #[serde(rename = "STU")]
        pub stu: String,
        #[serde(rename = "ENX")]
        pub enx: String,
        #[serde(rename = "TWO")]
        pub two: String,
        #[serde(rename = "HAM")]
        pub ham: String,
        #[serde(rename = "MUN")]
        pub mun: String,
        #[serde(rename = "DUS")]
        pub dus: String,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: String,
        #[serde(rename = "GER")]
        pub ger: String,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: String,
        #[serde(rename = "HAN")]
        pub han: String,
        #[serde(rename = "SAU")]
        pub sau: String,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: String,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: String,
        #[serde(rename = "OSL")]
        pub osl: String,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: String,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: String,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: String,
        #[serde(rename = "AMS")]
        pub ams: String,
        #[serde(rename = "ATH")]
        pub ath: String,
        #[serde(rename = "PNK")]
        pub pnk: String,
        #[serde(rename = "AQS")]
        pub aqs: String,
        #[serde(rename = "CPH")]
        pub cph: String,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: String,
        #[serde(rename = "NCM")]
        pub ncm: String,
        #[serde(rename = "NMS")]
        pub nms: String,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: String,
        #[serde(rename = "EBS")]
        pub ebs: String,
        #[serde(rename = "ASE")]
        pub ase: String,
        #[serde(rename = "BUE")]
        pub bue: String,
        #[serde(rename = "SGO")]
        pub sgo: String,
        #[serde(rename = "CNQ")]
        pub cnq: String,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: String,
        #[serde(rename = "TLV")]
        pub tlv: String,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: String,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: String,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: String,
        #[serde(rename = "LIS")]
        pub lis: String,
        #[serde(rename = "LIT")]
        pub lit: String,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: String,
        #[serde(rename = "ICE")]
        pub ice: String,
        #[serde(rename = "RIS")]
        pub ris: String,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: String,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Website {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: String,
        #[serde(rename = "STU")]
        pub stu: String,
        #[serde(rename = "ENX")]
        pub enx: String,
        #[serde(rename = "TWO")]
        pub two: String,
        #[serde(rename = "HAM")]
        pub ham: String,
        #[serde(rename = "MUN")]
        pub mun: String,
        #[serde(rename = "DUS")]
        pub dus: String,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: String,
        #[serde(rename = "GER")]
        pub ger: String,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: Value,
        #[serde(rename = "HAN")]
        pub han: String,
        #[serde(rename = "SAU")]
        pub sau: String,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: String,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: String,
        #[serde(rename = "OSL")]
        pub osl: String,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: String,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: String,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: String,
        #[serde(rename = "AMS")]
        pub ams: String,
        #[serde(rename = "ATH")]
        pub ath: String,
        #[serde(rename = "PNK")]
        pub pnk: String,
        #[serde(rename = "AQS")]
        pub aqs: String,
        #[serde(rename = "CPH")]
        pub cph: String,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: String,
        #[serde(rename = "NCM")]
        pub ncm: String,
        #[serde(rename = "NMS")]
        pub nms: String,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: String,
        #[serde(rename = "EBS")]
        pub ebs: String,
        #[serde(rename = "ASE")]
        pub ase: String,
        #[serde(rename = "BUE")]
        pub bue: String,
        #[serde(rename = "SGO")]
        pub sgo: String,
        #[serde(rename = "CNQ")]
        pub cnq: String,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: String,
        #[serde(rename = "TLV")]
        pub tlv: String,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: String,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: String,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: String,
        #[serde(rename = "LIS")]
        pub lis: String,
        #[serde(rename = "LIT")]
        pub lit: String,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: String,
        #[serde(rename = "ICE")]
        pub ice: String,
        #[serde(rename = "RIS")]
        pub ris: String,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: String,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct MarketOpen {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: String,
        #[serde(rename = "STU")]
        pub stu: String,
        #[serde(rename = "ENX")]
        pub enx: String,
        #[serde(rename = "TWO")]
        pub two: String,
        #[serde(rename = "HAM")]
        pub ham: String,
        #[serde(rename = "MUN")]
        pub mun: String,
        #[serde(rename = "DUS")]
        pub dus: String,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: String,
        #[serde(rename = "GER")]
        pub ger: String,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: String,
        #[serde(rename = "HAN")]
        pub han: String,
        #[serde(rename = "SAU")]
        pub sau: String,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: String,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: String,
        #[serde(rename = "OSL")]
        pub osl: String,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: String,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: String,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: String,
        #[serde(rename = "AMS")]
        pub ams: String,
        #[serde(rename = "ATH")]
        pub ath: String,
        #[serde(rename = "PNK")]
        pub pnk: String,
        #[serde(rename = "AQS")]
        pub aqs: String,
        #[serde(rename = "CPH")]
        pub cph: String,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: String,
        #[serde(rename = "NCM")]
        pub ncm: String,
        #[serde(rename = "NMS")]
        pub nms: String,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: String,
        #[serde(rename = "EBS")]
        pub ebs: String,
        #[serde(rename = "ASE")]
        pub ase: String,
        #[serde(rename = "BUE")]
        pub bue: String,
        #[serde(rename = "SGO")]
        pub sgo: String,
        #[serde(rename = "CNQ")]
        pub cnq: String,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: String,
        #[serde(rename = "TLV")]
        pub tlv: String,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: String,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: String,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: String,
        #[serde(rename = "LIS")]
        pub lis: String,
        #[serde(rename = "LIT")]
        pub lit: String,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: String,
        #[serde(rename = "ICE")]
        pub ice: String,
        #[serde(rename = "RIS")]
        pub ris: String,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: String,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct MarketClose {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: String,
        #[serde(rename = "STU")]
        pub stu: String,
        #[serde(rename = "ENX")]
        pub enx: String,
        #[serde(rename = "TWO")]
        pub two: String,
        #[serde(rename = "HAM")]
        pub ham: String,
        #[serde(rename = "MUN")]
        pub mun: String,
        #[serde(rename = "DUS")]
        pub dus: String,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: String,
        #[serde(rename = "GER")]
        pub ger: String,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: String,
        #[serde(rename = "HAN")]
        pub han: String,
        #[serde(rename = "SAU")]
        pub sau: String,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: String,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: String,
        #[serde(rename = "OSL")]
        pub osl: String,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: String,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: String,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: String,
        #[serde(rename = "AMS")]
        pub ams: String,
        #[serde(rename = "ATH")]
        pub ath: String,
        #[serde(rename = "PNK")]
        pub pnk: String,
        #[serde(rename = "AQS")]
        pub aqs: String,
        #[serde(rename = "CPH")]
        pub cph: String,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: String,
        #[serde(rename = "NCM")]
        pub ncm: String,
        #[serde(rename = "NMS")]
        pub nms: String,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: String,
        #[serde(rename = "EBS")]
        pub ebs: String,
        #[serde(rename = "ASE")]
        pub ase: String,
        #[serde(rename = "BUE")]
        pub bue: String,
        #[serde(rename = "SGO")]
        pub sgo: String,
        #[serde(rename = "CNQ")]
        pub cnq: String,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: String,
        #[serde(rename = "TLV")]
        pub tlv: String,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: String,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: String,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: String,
        #[serde(rename = "LIS")]
        pub lis: String,
        #[serde(rename = "LIT")]
        pub lit: String,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: String,
        #[serde(rename = "ICE")]
        pub ice: String,
        #[serde(rename = "RIS")]
        pub ris: String,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: String,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct LunchbreakStart {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: Value,
        #[serde(rename = "KOE")]
        pub koe: Value,
        #[serde(rename = "HKG")]
        pub hkg: Value,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: Value,
        #[serde(rename = "STU")]
        pub stu: Value,
        #[serde(rename = "ENX")]
        pub enx: Value,
        #[serde(rename = "TWO")]
        pub two: Value,
        #[serde(rename = "HAM")]
        pub ham: Value,
        #[serde(rename = "MUN")]
        pub mun: Value,
        #[serde(rename = "DUS")]
        pub dus: Value,
        #[serde(rename = "TW")]
        pub tw: Value,
        #[serde(rename = "PAR")]
        pub par: Value,
        #[serde(rename = "GER")]
        pub ger: Value,
        #[serde(rename = "IOB")]
        pub iob: Value,
        #[serde(rename = "LSE")]
        pub lse: Value,
        #[serde(rename = "MEX")]
        pub mex: Value,
        #[serde(rename = "HAN")]
        pub han: Value,
        #[serde(rename = "SAU")]
        pub sau: Value,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: Value,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: Value,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: Value,
        #[serde(rename = "VIE")]
        pub vie: Value,
        #[serde(rename = "BSE")]
        pub bse: Value,
        #[serde(rename = "OSL")]
        pub osl: Value,
        #[serde(rename = "NSI")]
        pub nsi: Value,
        #[serde(rename = "STO")]
        pub sto: Value,
        #[serde(rename = "MCE")]
        pub mce: Value,
        #[serde(rename = "MIL")]
        pub mil: Value,
        #[serde(rename = "BUD")]
        pub bud: Value,
        #[serde(rename = "SHH")]
        pub shh: Value,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: Value,
        #[serde(rename = "VAN")]
        pub van: Value,
        #[serde(rename = "SAO")]
        pub sao: Value,
        #[serde(rename = "ISE")]
        pub ise: Value,
        #[serde(rename = "AMS")]
        pub ams: Value,
        #[serde(rename = "ATH")]
        pub ath: Value,
        #[serde(rename = "PNK")]
        pub pnk: Value,
        #[serde(rename = "AQS")]
        pub aqs: Value,
        #[serde(rename = "CPH")]
        pub cph: Value,
        #[serde(rename = "TOR")]
        pub tor: Value,
        #[serde(rename = "NGM")]
        pub ngm: Value,
        #[serde(rename = "NCM")]
        pub ncm: Value,
        #[serde(rename = "NMS")]
        pub nms: Value,
        #[serde(rename = "CSE")]
        pub cse: Value,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: Value,
        #[serde(rename = "EBS")]
        pub ebs: Value,
        #[serde(rename = "ASE")]
        pub ase: Value,
        #[serde(rename = "BUE")]
        pub bue: Value,
        #[serde(rename = "SGO")]
        pub sgo: Value,
        #[serde(rename = "CNQ")]
        pub cnq: Value,
        #[serde(rename = "NZE")]
        pub nze: Value,
        #[serde(rename = "CCS")]
        pub ccs: Value,
        #[serde(rename = "JNB")]
        pub jnb: Value,
        #[serde(rename = "BRU")]
        pub bru: Value,
        #[serde(rename = "TLV")]
        pub tlv: Value,
        #[serde(rename = "DOH")]
        pub doh: Value,
        #[serde(rename = "MCX")]
        pub mcx: Value,
        #[serde(rename = "NEO")]
        pub neo: Value,
        #[serde(rename = "NYS")]
        pub nys: Value,
        #[serde(rename = "IST")]
        pub ist: Value,
        #[serde(rename = "NAS")]
        pub nas: Value,
        #[serde(rename = "LIS")]
        pub lis: Value,
        #[serde(rename = "LIT")]
        pub lit: Value,
        #[serde(rename = "PRA")]
        pub pra: Value,
        #[serde(rename = "TAL")]
        pub tal: Value,
        #[serde(rename = "ICE")]
        pub ice: Value,
        #[serde(rename = "RIS")]
        pub ris: Value,
        #[serde(rename = "CAI")]
        pub cai: Value,
        #[serde(rename = "PCX")]
        pub pcx: Value,
        #[serde(rename = "SAT")]
        pub sat: Value,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct LunchbreakEnd {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: Value,
        #[serde(rename = "KOE")]
        pub koe: Value,
        #[serde(rename = "HKG")]
        pub hkg: Value,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: Value,
        #[serde(rename = "STU")]
        pub stu: Value,
        #[serde(rename = "ENX")]
        pub enx: Value,
        #[serde(rename = "TWO")]
        pub two: Value,
        #[serde(rename = "HAM")]
        pub ham: Value,
        #[serde(rename = "MUN")]
        pub mun: Value,
        #[serde(rename = "DUS")]
        pub dus: Value,
        #[serde(rename = "TW")]
        pub tw: Value,
        #[serde(rename = "PAR")]
        pub par: Value,
        #[serde(rename = "GER")]
        pub ger: Value,
        #[serde(rename = "IOB")]
        pub iob: Value,
        #[serde(rename = "LSE")]
        pub lse: Value,
        #[serde(rename = "MEX")]
        pub mex: Value,
        #[serde(rename = "HAN")]
        pub han: Value,
        #[serde(rename = "SAU")]
        pub sau: Value,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: Value,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: Value,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: Value,
        #[serde(rename = "VIE")]
        pub vie: Value,
        #[serde(rename = "BSE")]
        pub bse: Value,
        #[serde(rename = "OSL")]
        pub osl: Value,
        #[serde(rename = "NSI")]
        pub nsi: Value,
        #[serde(rename = "STO")]
        pub sto: Value,
        #[serde(rename = "MCE")]
        pub mce: Value,
        #[serde(rename = "MIL")]
        pub mil: Value,
        #[serde(rename = "BUD")]
        pub bud: Value,
        #[serde(rename = "SHH")]
        pub shh: Value,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: Value,
        #[serde(rename = "VAN")]
        pub van: Value,
        #[serde(rename = "SAO")]
        pub sao: Value,
        #[serde(rename = "ISE")]
        pub ise: Value,
        #[serde(rename = "AMS")]
        pub ams: Value,
        #[serde(rename = "ATH")]
        pub ath: Value,
        #[serde(rename = "PNK")]
        pub pnk: Value,
        #[serde(rename = "AQS")]
        pub aqs: Value,
        #[serde(rename = "CPH")]
        pub cph: Value,
        #[serde(rename = "TOR")]
        pub tor: Value,
        #[serde(rename = "NGM")]
        pub ngm: Value,
        #[serde(rename = "NCM")]
        pub ncm: Value,
        #[serde(rename = "NMS")]
        pub nms: Value,
        #[serde(rename = "CSE")]
        pub cse: Value,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: Value,
        #[serde(rename = "EBS")]
        pub ebs: Value,
        #[serde(rename = "ASE")]
        pub ase: Value,
        #[serde(rename = "BUE")]
        pub bue: Value,
        #[serde(rename = "SGO")]
        pub sgo: Value,
        #[serde(rename = "CNQ")]
        pub cnq: Value,
        #[serde(rename = "NZE")]
        pub nze: Value,
        #[serde(rename = "CCS")]
        pub ccs: Value,
        #[serde(rename = "JNB")]
        pub jnb: Value,
        #[serde(rename = "BRU")]
        pub bru: Value,
        #[serde(rename = "TLV")]
        pub tlv: Value,
        #[serde(rename = "DOH")]
        pub doh: Value,
        #[serde(rename = "MCX")]
        pub mcx: Value,
        #[serde(rename = "NEO")]
        pub neo: Value,
        #[serde(rename = "NYS")]
        pub nys: Value,
        #[serde(rename = "IST")]
        pub ist: Value,
        #[serde(rename = "NAS")]
        pub nas: Value,
        #[serde(rename = "LIS")]
        pub lis: Value,
        #[serde(rename = "LIT")]
        pub lit: Value,
        #[serde(rename = "PRA")]
        pub pra: Value,
        #[serde(rename = "TAL")]
        pub tal: Value,
        #[serde(rename = "ICE")]
        pub ice: Value,
        #[serde(rename = "RIS")]
        pub ris: Value,
        #[serde(rename = "CAI")]
        pub cai: Value,
        #[serde(rename = "PCX")]
        pub pcx: Value,
        #[serde(rename = "SAT")]
        pub sat: Value,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct OpeningAuctionStart {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: Value,
        #[serde(rename = "STU")]
        pub stu: Value,
        #[serde(rename = "ENX")]
        pub enx: Value,
        #[serde(rename = "TWO")]
        pub two: Value,
        #[serde(rename = "HAM")]
        pub ham: Value,
        #[serde(rename = "MUN")]
        pub mun: Value,
        #[serde(rename = "DUS")]
        pub dus: Value,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: Value,
        #[serde(rename = "GER")]
        pub ger: Value,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: Value,
        #[serde(rename = "HAN")]
        pub han: Value,
        #[serde(rename = "SAU")]
        pub sau: Value,
        #[serde(rename = "JPX")]
        pub jpx: Value,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: Value,
        #[serde(rename = "FKA")]
        pub fka: Value,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: Value,
        #[serde(rename = "OSL")]
        pub osl: Value,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: Value,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: Value,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: Value,
        #[serde(rename = "AMS")]
        pub ams: Value,
        #[serde(rename = "ATH")]
        pub ath: Value,
        #[serde(rename = "PNK")]
        pub pnk: Value,
        #[serde(rename = "AQS")]
        pub aqs: Value,
        #[serde(rename = "CPH")]
        pub cph: Value,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: Value,
        #[serde(rename = "NCM")]
        pub ncm: Value,
        #[serde(rename = "NMS")]
        pub nms: Value,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: Value,
        #[serde(rename = "EBS")]
        pub ebs: Value,
        #[serde(rename = "ASE")]
        pub ase: Value,
        #[serde(rename = "BUE")]
        pub bue: Value,
        #[serde(rename = "SGO")]
        pub sgo: Value,
        #[serde(rename = "CNQ")]
        pub cnq: Value,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: Value,
        #[serde(rename = "TLV")]
        pub tlv: Value,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: Value,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: Value,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: Value,
        #[serde(rename = "LIS")]
        pub lis: Value,
        #[serde(rename = "LIT")]
        pub lit: Value,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: Value,
        #[serde(rename = "ICE")]
        pub ice: Value,
        #[serde(rename = "RIS")]
        pub ris: Value,
        #[serde(rename = "CAI")]
        pub cai: Value,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: Value,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct OpeningAuctionEnd {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: Value,
        #[serde(rename = "STU")]
        pub stu: Value,
        #[serde(rename = "ENX")]
        pub enx: Value,
        #[serde(rename = "TWO")]
        pub two: Value,
        #[serde(rename = "HAM")]
        pub ham: Value,
        #[serde(rename = "MUN")]
        pub mun: Value,
        #[serde(rename = "DUS")]
        pub dus: Value,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: Value,
        #[serde(rename = "GER")]
        pub ger: Value,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: Value,
        #[serde(rename = "HAN")]
        pub han: Value,
        #[serde(rename = "SAU")]
        pub sau: Value,
        #[serde(rename = "JPX")]
        pub jpx: Value,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: Value,
        #[serde(rename = "FKA")]
        pub fka: Value,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: Value,
        #[serde(rename = "OSL")]
        pub osl: Value,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: Value,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: Value,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: Value,
        #[serde(rename = "AMS")]
        pub ams: Value,
        #[serde(rename = "ATH")]
        pub ath: Value,
        #[serde(rename = "PNK")]
        pub pnk: Value,
        #[serde(rename = "AQS")]
        pub aqs: Value,
        #[serde(rename = "CPH")]
        pub cph: Value,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: Value,
        #[serde(rename = "NCM")]
        pub ncm: Value,
        #[serde(rename = "NMS")]
        pub nms: Value,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: Value,
        #[serde(rename = "EBS")]
        pub ebs: Value,
        #[serde(rename = "ASE")]
        pub ase: Value,
        #[serde(rename = "BUE")]
        pub bue: Value,
        #[serde(rename = "SGO")]
        pub sgo: Value,
        #[serde(rename = "CNQ")]
        pub cnq: Value,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: Value,
        #[serde(rename = "TLV")]
        pub tlv: Value,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: Value,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: Value,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: Value,
        #[serde(rename = "LIS")]
        pub lis: Value,
        #[serde(rename = "LIT")]
        pub lit: Value,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: Value,
        #[serde(rename = "ICE")]
        pub ice: Value,
        #[serde(rename = "RIS")]
        pub ris: Value,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: Value,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ClosingAuctionStart {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: Value,
        #[serde(rename = "STU")]
        pub stu: Value,
        #[serde(rename = "ENX")]
        pub enx: Value,
        #[serde(rename = "TWO")]
        pub two: Value,
        #[serde(rename = "HAM")]
        pub ham: Value,
        #[serde(rename = "MUN")]
        pub mun: Value,
        #[serde(rename = "DUS")]
        pub dus: Value,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: Value,
        #[serde(rename = "GER")]
        pub ger: Value,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: Value,
        #[serde(rename = "HAN")]
        pub han: Value,
        #[serde(rename = "SAU")]
        pub sau: Value,
        #[serde(rename = "JPX")]
        pub jpx: Value,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: Value,
        #[serde(rename = "FKA")]
        pub fka: Value,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: Value,
        #[serde(rename = "OSL")]
        pub osl: Value,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: Value,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: Value,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: Value,
        #[serde(rename = "AMS")]
        pub ams: Value,
        #[serde(rename = "ATH")]
        pub ath: Value,
        #[serde(rename = "PNK")]
        pub pnk: Value,
        #[serde(rename = "AQS")]
        pub aqs: Value,
        #[serde(rename = "CPH")]
        pub cph: Value,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: Value,
        #[serde(rename = "NCM")]
        pub ncm: Value,
        #[serde(rename = "NMS")]
        pub nms: Value,
        #[serde(rename = "CSE")]
        pub cse: Value,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: Value,
        #[serde(rename = "EBS")]
        pub ebs: Value,
        #[serde(rename = "ASE")]
        pub ase: Value,
        #[serde(rename = "BUE")]
        pub bue: Value,
        #[serde(rename = "SGO")]
        pub sgo: Value,
        #[serde(rename = "CNQ")]
        pub cnq: Value,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: Value,
        #[serde(rename = "TLV")]
        pub tlv: Value,
        #[serde(rename = "DOH")]
        pub doh: Value,
        #[serde(rename = "MCX")]
        pub mcx: Value,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: Value,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: Value,
        #[serde(rename = "LIS")]
        pub lis: Value,
        #[serde(rename = "LIT")]
        pub lit: Value,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: Value,
        #[serde(rename = "ICE")]
        pub ice: Value,
        #[serde(rename = "RIS")]
        pub ris: Value,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: Value,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct ClosingAuctionEnd {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: Value,
        #[serde(rename = "STU")]
        pub stu: Value,
        #[serde(rename = "ENX")]
        pub enx: Value,
        #[serde(rename = "TWO")]
        pub two: Value,
        #[serde(rename = "HAM")]
        pub ham: Value,
        #[serde(rename = "MUN")]
        pub mun: Value,
        #[serde(rename = "DUS")]
        pub dus: Value,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: Value,
        #[serde(rename = "GER")]
        pub ger: Value,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: Value,
        #[serde(rename = "HAN")]
        pub han: Value,
        #[serde(rename = "SAU")]
        pub sau: Value,
        #[serde(rename = "JPX")]
        pub jpx: Value,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: Value,
        #[serde(rename = "FKA")]
        pub fka: Value,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: Value,
        #[serde(rename = "OSL")]
        pub osl: Value,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: Value,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: Value,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: Value,
        #[serde(rename = "AMS")]
        pub ams: Value,
        #[serde(rename = "ATH")]
        pub ath: Value,
        #[serde(rename = "PNK")]
        pub pnk: Value,
        #[serde(rename = "AQS")]
        pub aqs: Value,
        #[serde(rename = "CPH")]
        pub cph: Value,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: Value,
        #[serde(rename = "NCM")]
        pub ncm: Value,
        #[serde(rename = "NMS")]
        pub nms: Value,
        #[serde(rename = "CSE")]
        pub cse: Value,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: Value,
        #[serde(rename = "EBS")]
        pub ebs: Value,
        #[serde(rename = "ASE")]
        pub ase: Value,
        #[serde(rename = "BUE")]
        pub bue: Value,
        #[serde(rename = "SGO")]
        pub sgo: Value,
        #[serde(rename = "CNQ")]
        pub cnq: Value,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: Value,
        #[serde(rename = "TLV")]
        pub tlv: Value,
        #[serde(rename = "DOH")]
        pub doh: Value,
        #[serde(rename = "MCX")]
        pub mcx: Value,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: Value,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: Value,
        #[serde(rename = "LIS")]
        pub lis: Value,
        #[serde(rename = "LIT")]
        pub lit: Value,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: Value,
        #[serde(rename = "ICE")]
        pub ice: Value,
        #[serde(rename = "RIS")]
        pub ris: Value,
        #[serde(rename = "CAI")]
        pub cai: Value,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: Value,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Timezone {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: String,
        #[serde(rename = "STU")]
        pub stu: String,
        #[serde(rename = "ENX")]
        pub enx: String,
        #[serde(rename = "TWO")]
        pub two: String,
        #[serde(rename = "HAM")]
        pub ham: String,
        #[serde(rename = "MUN")]
        pub mun: String,
        #[serde(rename = "DUS")]
        pub dus: String,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: String,
        #[serde(rename = "GER")]
        pub ger: String,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: String,
        #[serde(rename = "HAN")]
        pub han: String,
        #[serde(rename = "SAU")]
        pub sau: String,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: String,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: String,
        #[serde(rename = "OSL")]
        pub osl: String,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: String,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: String,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: String,
        #[serde(rename = "AMS")]
        pub ams: String,
        #[serde(rename = "ATH")]
        pub ath: String,
        #[serde(rename = "PNK")]
        pub pnk: String,
        #[serde(rename = "AQS")]
        pub aqs: String,
        #[serde(rename = "CPH")]
        pub cph: String,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: String,
        #[serde(rename = "NCM")]
        pub ncm: String,
        #[serde(rename = "NMS")]
        pub nms: String,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: String,
        #[serde(rename = "EBS")]
        pub ebs: String,
        #[serde(rename = "ASE")]
        pub ase: String,
        #[serde(rename = "BUE")]
        pub bue: String,
        #[serde(rename = "SGO")]
        pub sgo: String,
        #[serde(rename = "CNQ")]
        pub cnq: String,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: String,
        #[serde(rename = "TLV")]
        pub tlv: String,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: String,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: String,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: String,
        #[serde(rename = "LIS")]
        pub lis: String,
        #[serde(rename = "LIT")]
        pub lit: String,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: String,
        #[serde(rename = "ICE")]
        pub ice: String,
        #[serde(rename = "RIS")]
        pub ris: String,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: String,
    }

    #[derive(Debug, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    pub struct Flag {
        #[serde(rename = "SHZ")]
        pub shz: String,
        #[serde(rename = "KSC")]
        pub ksc: String,
        #[serde(rename = "KOE")]
        pub koe: String,
        #[serde(rename = "HKG")]
        pub hkg: String,
        #[serde(rename = "KLS")]
        pub kls: String,
        #[serde(rename = "FRA")]
        pub fra: String,
        #[serde(rename = "STU")]
        pub stu: String,
        #[serde(rename = "ENX")]
        pub enx: String,
        #[serde(rename = "TWO")]
        pub two: String,
        #[serde(rename = "HAM")]
        pub ham: String,
        #[serde(rename = "MUN")]
        pub mun: String,
        #[serde(rename = "DUS")]
        pub dus: String,
        #[serde(rename = "TW")]
        pub tw: String,
        #[serde(rename = "PAR")]
        pub par: String,
        #[serde(rename = "GER")]
        pub ger: String,
        #[serde(rename = "IOB")]
        pub iob: String,
        #[serde(rename = "LSE")]
        pub lse: String,
        #[serde(rename = "MEX")]
        pub mex: String,
        #[serde(rename = "HAN")]
        pub han: String,
        #[serde(rename = "SAU")]
        pub sau: String,
        #[serde(rename = "JPX")]
        pub jpx: String,
        #[serde(rename = "ASX")]
        pub asx: String,
        #[serde(rename = "SAP")]
        pub sap: String,
        #[serde(rename = "FKA")]
        pub fka: String,
        #[serde(rename = "SES")]
        pub ses: String,
        #[serde(rename = "TLO")]
        pub tlo: String,
        #[serde(rename = "VIE")]
        pub vie: String,
        #[serde(rename = "BSE")]
        pub bse: String,
        #[serde(rename = "OSL")]
        pub osl: String,
        #[serde(rename = "NSI")]
        pub nsi: String,
        #[serde(rename = "STO")]
        pub sto: String,
        #[serde(rename = "MCE")]
        pub mce: String,
        #[serde(rename = "MIL")]
        pub mil: String,
        #[serde(rename = "BUD")]
        pub bud: String,
        #[serde(rename = "SHH")]
        pub shh: String,
        #[serde(rename = "SET")]
        pub set: String,
        #[serde(rename = "NYQ")]
        pub nyq: String,
        #[serde(rename = "VAN")]
        pub van: String,
        #[serde(rename = "SAO")]
        pub sao: String,
        #[serde(rename = "ISE")]
        pub ise: String,
        #[serde(rename = "AMS")]
        pub ams: String,
        #[serde(rename = "ATH")]
        pub ath: String,
        #[serde(rename = "PNK")]
        pub pnk: String,
        #[serde(rename = "AQS")]
        pub aqs: String,
        #[serde(rename = "CPH")]
        pub cph: String,
        #[serde(rename = "TOR")]
        pub tor: String,
        #[serde(rename = "NGM")]
        pub ngm: String,
        #[serde(rename = "NCM")]
        pub ncm: String,
        #[serde(rename = "NMS")]
        pub nms: String,
        #[serde(rename = "CSE")]
        pub cse: String,
        #[serde(rename = "JKT")]
        pub jkt: String,
        #[serde(rename = "HEL")]
        pub hel: String,
        #[serde(rename = "EBS")]
        pub ebs: String,
        #[serde(rename = "ASE")]
        pub ase: String,
        #[serde(rename = "BUE")]
        pub bue: String,
        #[serde(rename = "SGO")]
        pub sgo: String,
        #[serde(rename = "CNQ")]
        pub cnq: String,
        #[serde(rename = "NZE")]
        pub nze: String,
        #[serde(rename = "CCS")]
        pub ccs: String,
        #[serde(rename = "JNB")]
        pub jnb: String,
        #[serde(rename = "BRU")]
        pub bru: String,
        #[serde(rename = "TLV")]
        pub tlv: String,
        #[serde(rename = "DOH")]
        pub doh: String,
        #[serde(rename = "MCX")]
        pub mcx: String,
        #[serde(rename = "NEO")]
        pub neo: String,
        #[serde(rename = "NYS")]
        pub nys: String,
        #[serde(rename = "IST")]
        pub ist: String,
        #[serde(rename = "NAS")]
        pub nas: String,
        #[serde(rename = "LIS")]
        pub lis: String,
        #[serde(rename = "LIT")]
        pub lit: String,
        #[serde(rename = "PRA")]
        pub pra: String,
        #[serde(rename = "TAL")]
        pub tal: String,
        #[serde(rename = "ICE")]
        pub ice: String,
        #[serde(rename = "RIS")]
        pub ris: String,
        #[serde(rename = "CAI")]
        pub cai: String,
        #[serde(rename = "PCX")]
        pub pcx: String,
        #[serde(rename = "SAT")]
        pub sat: String,
    }
}
